name: "Check Merge Source"
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize, ready_for_review]

jobs:
  check_source_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify source branch is dev
        if: github.head_ref != 'dev'
        run: |
          echo "ERROR: Solo se permiten merges a 'main' desde la rama 'dev'."
          echo "Tu rama de origen es: ${{ github.head_ref }}"
          exit 1
